// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPq7pZoZZa-qF6t4d6C5gyxFdsdOgYq0',
    appId: '1:322673876171:android:c084e834ac2599c8a44f4e',
    messagingSenderId: '322673876171',
    projectId: 'ecommerce-95160',
    storageBucket: 'ecommerce-95160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-ufg7JhuIpll8qtHSwrS4POhJU-Cm8A',
    appId: '1:322673876171:ios:94e95188b6fbf641a44f4e',
    messagingSenderId: '322673876171',
    projectId: 'ecommerce-95160',
    storageBucket: 'ecommerce-95160.appspot.com',
    androidClientId: '322673876171-hp6ualeock4c4cdgu53mrcd91o4g7qlf.apps.googleusercontent.com',
    iosClientId: '322673876171-njdl36v08mrknsc1ocm5e1pqt2id1jni.apps.googleusercontent.com',
    iosBundleId: 'com.example.myshopp',
  );
}
